import layout from './img/newsImages/layout.jpeg'
import ledipico from './img/newsImages/LEPIDICO-SIGNING.jpeg'
import sheep from './img/sheep.jpeg'

export const newData = [
  {
    "id": 1,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 2,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 3,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 4,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 5,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 6,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 7,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 8,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 9,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 10,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 11,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 12,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 13,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 14,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 15,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 16,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 17,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 18,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 19,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 20,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 21,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 22,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 23,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 24,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 25,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 26,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 27,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 28,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
  {
    "id": 29,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": layout,
  },
  {
    "id": 30,
    "date": "January, 2 2022",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    "image": ledipico,
  },
]